project:
  type: website

website:
  title: "Experimental Design"
  page-navigation: true
  navbar:
    logo: "assets/bijans-projects-logo.png"
    left:
      - text: "Home"
        href: index.qmd
      - text: "Explorations"
        href: explorations/index.qmd
      - text: "Assignments"
        href: assignments/index.qmd
    tools:
      - icon: github
        menu:
          - text: Source Code (Repo)
            href: https://github.com/Bijans-Projects/design-and-analysis-of-experiments-posit-quarto
  sidebar:
    - id: explorations
      title: "Explorations"
      style: "floating"
      search: true
      contents: 
        - section: "Explorations"
          href: explorations/index.qmd
          contents:
            - explorations/e1.qmd
            - explorations/e2.qmd
    
    - id: "assignments"
      title: "Assignments"
      contents:
        - assignments/index.qmd
        - assignments/a01.qmd


format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



